# Generated by Django 3.2.24 on 2025-07-21 19:38

from django.db import migrations, models
import mock.models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0008_mockapiresponsehandler_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockapiresponsehandler',
            name='api',
        ),
        migrations.AlterField(
            model_name='mockproject',
            name='project_id',
            field=models.CharField(default=mock.models.generate_short_id, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='mockapilog',
            index=models.Index(fields=['create_time'], name='mock_api_lo_create__348159_idx'),
        ),
        migrations.AddIndex(
            model_name='mockapilog',
            index=models.Index(fields=['request_id'], name='mock_api_lo_request_bcb6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='mockapilog',
            index=models.Index(fields=['api_id'], name='mock_api_lo_api_id_c83ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='mockapilog',
            index=models.Index(fields=['project_id'], name='mock_api_lo_project_1b0643_idx'),
        ),
        migrations.DeleteModel(
            name='MockAPIResponseHandler',
        ),
    ]
